version: '3.8'

services:
  redis:
    container_name: wstrade-portfolio-redis
    image: redis
    ports:
      - 6379:6379

  mongo:
    container_name: wstrade-portfolio-mongo
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  mongo-express:
    container_name: wstrade-portfolio-mongo-express
    image: mongo-express
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_USERNAME}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
      ME_CONFIG_MONGODB_URL: mongodb://${DB_USERNAME}:${DB_PASSWORD}@mongo:27017

  # app:
  #   container_name: wstrade-portfolio-app
  #   build: .
  #   depends_on:
  #     - redis
  #     - mongo
  #   ports:
  #     - 8080:8080
